// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7TjkORAXk4qmTRFr9beSVKlepdu5Jr8',
    appId: '1:472329781692:web:362e0fd85c6645c326abb9',
    messagingSenderId: '472329781692',
    projectId: 'calindga-app',
    authDomain: 'calindga-app.firebaseapp.com',
    storageBucket: 'calindga-app.firebasestorage.app',
    measurementId: 'G-538778GZN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7mCsVpuXEGsPP3l1grGb8o8qKFrslso',
    appId: '1:472329781692:android:bfdb67cd83684dd826abb9',
    messagingSenderId: '472329781692',
    projectId: 'calindga-app',
    storageBucket: 'calindga-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzAUmNUC_u1QmqVVyJgygmdvetvZqJnvo',
    appId: '1:472329781692:ios:013b1f6d9afd68a026abb9',
    messagingSenderId: '472329781692',
    projectId: 'calindga-app',
    storageBucket: 'calindga-app.firebasestorage.app',
    iosBundleId: 'com.myapp.calingaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzAUmNUC_u1QmqVVyJgygmdvetvZqJnvo',
    appId: '1:472329781692:ios:013b1f6d9afd68a026abb9',
    messagingSenderId: '472329781692',
    projectId: 'calindga-app',
    storageBucket: 'calindga-app.firebasestorage.app',
    iosBundleId: 'com.myapp.calingaFlutterApp',
  );
}
